<?php

namespace App\Http\Controllers;

use App\Models\MobileLibrarySchedule;
use Illuminate\Http\Request;

class ScheduleController extends Controller
{
    // Public schedule view - shows schedules generated by admin
    public function index(Request $request)
    {
        $place = trim((string) $request->query('place', ''));
        $booker = trim((string) $request->query('booker', ''));
        $category = trim((string) $request->query('category', ''));

        // Get schedules with reservation details
        // Only show upcoming schedules (end_time >= now) or ongoing events
        $query = MobileLibrarySchedule::query()
            ->with(['reservation' => function($q) {
                $q->select(['id','full_name','category','occupation','address','phone_number','gender','reservation_date','status','visit_time','duration_minutes']);
            }])
            ->where('end_time', '>=', now()) // Filter: only upcoming/ongoing schedules
            ->orderBy('scheduled_date')
            ->orderBy('start_time');

        // Filter by reservation details
        if ($place !== '' || $booker !== '' || $category !== '') {
            $query->whereHas('reservation', function($q) use ($place, $booker, $category) {
                if ($place !== '') {
                    $q->where('address', 'like', "%$place%");
                }
                if ($booker !== '') {
                    $q->where('full_name', 'like', "%$booker%");
                }
                if ($category !== '') {
                    $q->where('category', 'like', "%$category%");
                }
            });
        }

        $schedules = $query->paginate(24)->appends($request->query());

        return view('schedule.index', compact('schedules','place','booker','category'));
    }
}
