<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing books first (optional)
        // DB::table('books')->truncate();
        
        $books = [
            [
                'judul' => 'Harry Potter and the Philosopher\'s Stone',
                'penulis' => 'J.K. Rowling',
                'penerbit' => 'Bloomsbury',
                'tahun_terbit' => '1997',
                'ISBN' => '9780747532699',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Harry Potter yang berusia sebelas tahun menemukan bahwa ia adalah seorang penyihir dan memulai petualangannya di Hogwarts School of Witchcraft and Wizardry.',
                'jumlah_eksemplar' => 10,
                'cover_image' => 'harry-potter-1.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'To Kill a Mockingbird',
                'penulis' => 'Harper Lee',
                'penerbit' => 'J.B. Lippincott & Co.',
                'tahun_terbit' => '1960',
                'ISBN' => '9780061120084',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Novel klasik tentang rasisme dan ketidakadilan di Amerika Selatan tahun 1930-an, diceritakan melalui mata seorang anak kecil.',
                'jumlah_eksemplar' => 8,
                'cover_image' => 'mockingbird.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => '1984',
                'penulis' => 'George Orwell',
                'penerbit' => 'Secker & Warburg',
                'tahun_terbit' => '1949',
                'ISBN' => '9780451524935',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Novel dystopian tentang masyarakat totalitarian di bawah pengawasan konstan oleh "Big Brother".',
                'jumlah_eksemplar' => 12,
                'cover_image' => '1984.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Sejarah Indonesia Modern',
                'penulis' => 'Ricklefs, M.C.',
                'penerbit' => 'Gadjah Mada University Press',
                'tahun_terbit' => '2008',
                'ISBN' => '9789794202418',
                'kategori' => 'Biografi',
                'genre' => 'Non-Fiction',
                'deskripsi' => 'Buku komprehensif tentang sejarah Indonesia dari masa kolonial hingga era reformasi.',
                'jumlah_eksemplar' => 15,
                'cover_image' => 'sejarah-indonesia.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Laskar Pelangi',
                'penulis' => 'Andrea Hirata',
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => '2005',
                'ISBN' => '9789793062792',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Novel inspiratif tentang kehidupan dan perjuangan anak-anak di Belitung untuk mendapatkan pendidikan.',
                'jumlah_eksemplar' => 20,
                'cover_image' => 'laskar-pelangi.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Bumi Manusia',
                'penulis' => 'Pramoedya Ananta Toer',
                'penerbit' => 'Hasta Mitra',
                'tahun_terbit' => '1980',
                'ISBN' => '9789799731234',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Novel pertama dari Tetralogi Buru yang mengisahkan kehidupan di masa kolonial Belanda.',
                'jumlah_eksemplar' => 10,
                'cover_image' => 'bumi-manusia.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Sapiens: A Brief History of Humankind',
                'penulis' => 'Yuval Noah Harari',
                'penerbit' => 'Harper',
                'tahun_terbit' => '2014',
                'ISBN' => '9780062316097',
                'kategori' => 'Ensiklopedia',
                'genre' => 'Non-Fiction',
                'deskripsi' => 'Sejarah singkat umat manusia dari evolusi Homo sapiens hingga era modern.',
                'jumlah_eksemplar' => 18,
                'cover_image' => 'sapiens.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Ensiklopedia Biologi',
                'penulis' => 'Tim Penulis',
                'penerbit' => 'Erlangga',
                'tahun_terbit' => '2018',
                'ISBN' => '9786024341234',
                'kategori' => 'Ensiklopedia',
                'genre' => 'Education',
                'deskripsi' => 'Ensiklopedia lengkap tentang berbagai aspek biologi untuk pelajar dan umum.',
                'jumlah_eksemplar' => 7,
                'cover_image' => 'ensiklopedia-biologi.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'The Little Prince',
                'penulis' => 'Antoine de Saint-Exupéry',
                'penerbit' => 'Reynal & Hitchcock',
                'tahun_terbit' => '1943',
                'ISBN' => '9780156012195',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Cerita klasik tentang seorang pangeran kecil yang melakukan perjalanan dari planet ke planet.',
                'jumlah_eksemplar' => 14,
                'cover_image' => 'little-prince.jpg',
                'audience_category' => 'children',
                'created_at' => now(),
            ],
            [
                'judul' => 'Matematika untuk SMA',
                'penulis' => 'Tim Guru Indonesia',
                'penerbit' => 'Gramedia',
                'tahun_terbit' => '2020',
                'ISBN' => '9786020638234',
                'kategori' => 'Komik',
                'genre' => 'Education',
                'deskripsi' => 'Buku pelajaran matematika lengkap untuk siswa SMA kelas 10-12.',
                'jumlah_eksemplar' => 25,
                'cover_image' => 'matematika-sma.jpg',
                'audience_category' => 'students',
                'created_at' => now(),
            ],
            [
                'judul' => 'Ronggeng Dukuh Paruk',
                'penulis' => 'Ahmad Tohari',
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => '1982',
                'ISBN' => '9789792202076',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Novel tentang kehidupan ronggeng di sebuah dukuh terpencil di Jawa Tengah.',
                'jumlah_eksemplar' => 9,
                'cover_image' => 'ronggeng-dukuh-paruk.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Sejarah Peradaban Islam',
                'penulis' => 'Badri Yatim',
                'penerbit' => 'Raja Grafindo Persada',
                'tahun_terbit' => '2006',
                'ISBN' => '9789797693879',
                'kategori' => 'Biografi',
                'genre' => 'Non-Fiction',
                'deskripsi' => 'Buku tentang perkembangan peradaban Islam dari masa awal hingga modern.',
                'jumlah_eksemplar' => 11,
                'cover_image' => 'sejarah-islam.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            
            // === TAMBAHAN BUKU BARU ===
            
            // Fiksi Indonesia
            [
                'judul' => 'Cantik Itu Luka',
                'penulis' => 'Eka Kurniawan',
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => '2002',
                'ISBN' => '9789792218039',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Novel magis realis tentang Dewi Ayu, pelacur tercantik di kota kecil yang bangkit dari kubur setelah 21 tahun.',
                'jumlah_eksemplar' => 12,
                'cover_image' => 'cantik-itu-luka.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Ayat-Ayat Cinta',
                'penulis' => 'Habiburrahman El Shirazy',
                'penerbit' => 'Republika',
                'tahun_terbit' => '2004',
                'ISBN' => '9789793062808',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Novel romantis islami tentang Fahri, mahasiswa Indonesia di Mesir yang terjerat kisah cinta.',
                'jumlah_eksemplar' => 15,
                'cover_image' => 'ayat-ayat-cinta.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Sang Pemimpi',
                'penulis' => 'Andrea Hirata',
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => '2006',
                'ISBN' => '9789793062815',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Sekuel Laskar Pelangi. Kisah perjuangan Ikal dan Arai mengejar mimpi hingga ke Eropa.',
                'jumlah_eksemplar' => 14,
                'cover_image' => 'sang-pemimpi.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Tenggelamnya Kapal Van Der Wijck',
                'penulis' => 'Hamka',
                'penerbit' => 'Bulan Bintang',
                'tahun_terbit' => '1973',
                'ISBN' => '9789795110934',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Kisah cinta tragis Zainuddin dan Hayati yang terhalang perbedaan status sosial.',
                'jumlah_eksemplar' => 10,
                'cover_image' => 'kapal-van-der-wijck.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Perahu Kertas',
                'penulis' => 'Dee Lestari',
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => '2009',
                'ISBN' => '9789797806934',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Kisah cinta remaja tentang Kugy dan Keenan yang saling mengejar mimpi sambil mencari cinta sejati.',
                'jumlah_eksemplar' => 18,
                'cover_image' => 'perahu-kertas.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            
            // Pengembangan Diri & Motivasi
            [
                'judul' => 'Filosofi Teras',
                'penulis' => 'Henry Manampiring',
                'penerbit' => 'Kompas Gramedia',
                'tahun_terbit' => '2019',
                'ISBN' => '9786024246945',
                'kategori' => 'Ensiklopedia',
                'genre' => 'Non-Fiction',
                'deskripsi' => 'Filsafat Stoicisme untuk mengatasi anxiety dan stress di era modern.',
                'jumlah_eksemplar' => 22,
                'cover_image' => 'filosofi-teras.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Atomic Habits',
                'penulis' => 'James Clear',
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => '2019',
                'ISBN' => '9786020633176',
                'kategori' => 'Ensiklopedia',
                'genre' => 'Non-Fiction',
                'deskripsi' => 'Panduan praktis membangun kebiasaan baik dan menghilangkan kebiasaan buruk.',
                'jumlah_eksemplar' => 25,
                'cover_image' => 'atomic-habits.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Mindset: Psikologi Sukses',
                'penulis' => 'Carol S. Dweck',
                'penerbit' => 'Serambi Ilmu Semesta',
                'tahun_terbit' => '2017',
                'ISBN' => '9786024522667',
                'kategori' => 'Ensiklopedia',
                'genre' => 'Non-Fiction',
                'deskripsi' => 'Penelitian tentang growth mindset vs fixed mindset dalam mencapai kesuksesan.',
                'jumlah_eksemplar' => 16,
                'cover_image' => 'mindset.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'The 7 Habits of Highly Effective People',
                'penulis' => 'Stephen R. Covey',
                'penerbit' => 'Free Press',
                'tahun_terbit' => '1989',
                'ISBN' => '9780743269513',
                'kategori' => 'Ensiklopedia',
                'genre' => 'Non-Fiction',
                'deskripsi' => '7 kebiasaan orang yang sangat efektif untuk kesuksesan personal dan profesional.',
                'jumlah_eksemplar' => 19,
                'cover_image' => '7-habits.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            
            // Buku Anak-Anak
            [
                'judul' => 'Kancil dan Buaya',
                'penulis' => 'Tim Penulis Bhuana',
                'penerbit' => 'Bhuana Ilmu Populer',
                'tahun_terbit' => '2018',
                'ISBN' => '9786024525187',
                'kategori' => 'Komik',
                'genre' => 'Fiction',
                'deskripsi' => 'Cerita rakyat nusantara tentang kancil yang cerdik mengelabui buaya.',
                'jumlah_eksemplar' => 30,
                'cover_image' => 'kancil-buaya.jpg',
                'audience_category' => 'children',
                'created_at' => now(),
            ],
            [
                'judul' => 'Si Pitung: Pahlawan Betawi',
                'penulis' => 'Tim Penulis Gramedia',
                'penerbit' => 'Gramedia',
                'tahun_terbit' => '2019',
                'ISBN' => '9786020633145',
                'kategori' => 'Komik',
                'genre' => 'Fiction',
                'deskripsi' => 'Kisah heroik Si Pitung, jagoan Betawi yang melawan ketidakadilan.',
                'jumlah_eksemplar' => 20,
                'cover_image' => 'si-pitung.jpg',
                'audience_category' => 'children',
                'created_at' => now(),
            ],
            [
                'judul' => 'Petualangan Sherina',
                'penulis' => 'Jujur Prananto',
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => '2000',
                'ISBN' => '9789796867264',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Petualangan seru Sherina dan Sadam di perkebunan teh melawan penjahat.',
                'jumlah_eksemplar' => 15,
                'cover_image' => 'sherina.jpg',
                'audience_category' => 'children',
                'created_at' => now(),
            ],
            [
                'judul' => 'Keluarga Cemara',
                'penulis' => 'Arswendo Atmowiloto',
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => '2018',
                'ISBN' => '9786020630359',
                'kategori' => 'Novel',
                'genre' => 'Fiction',
                'deskripsi' => 'Cerita keluarga yang mengajarkan nilai kebersamaan dan kebahagiaan sederhana.',
                'jumlah_eksemplar' => 18,
                'cover_image' => 'keluarga-cemara.jpg',
                'audience_category' => 'children',
                'created_at' => now(),
            ],
            
            // Agama & Spiritual
            [
                'judul' => 'Al-Quran dan Terjemahan',
                'penulis' => 'Kementerian Agama RI',
                'penerbit' => 'Sygma',
                'tahun_terbit' => '2020',
                'ISBN' => '9786232160545',
                'kategori' => 'Biografi',
                'genre' => 'Religion',
                'deskripsi' => 'Al-Quran lengkap 30 juz dengan terjemahan bahasa Indonesia dan tajwid.',
                'jumlah_eksemplar' => 50,
                'cover_image' => 'alquran.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Tafsir Ibnu Katsir',
                'penulis' => 'Ibnu Katsir',
                'penerbit' => 'Pustaka Imam Syafi\'i',
                'tahun_terbit' => '2016',
                'ISBN' => '9786021613191',
                'kategori' => 'Biografi',
                'genre' => 'Religion',
                'deskripsi' => 'Tafsir Al-Quran lengkap dari Imam Ibnu Katsir yang terkenal.',
                'jumlah_eksemplar' => 12,
                'cover_image' => 'tafsir-ibnu-katsir.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Kitab Tauhid',
                'penulis' => 'Muhammad bin Abdul Wahhab',
                'penerbit' => 'Darul Haq',
                'tahun_terbit' => '2017',
                'ISBN' => '9786025734106',
                'kategori' => 'Biografi',
                'genre' => 'Religion',
                'deskripsi' => 'Kitab klasik tentang dasar-dasar tauhid dan keimanan dalam Islam.',
                'jumlah_eksemplar' => 20,
                'cover_image' => 'kitab-tauhid.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            
            // Komik & Manga
            [
                'judul' => 'Si Juki: Kumpulan Strip',
                'penulis' => 'Faza Meonk',
                'penerbit' => 'Bukune',
                'tahun_terbit' => '2019',
                'ISBN' => '9786237222026',
                'kategori' => 'Komik',
                'genre' => 'Fiction',
                'deskripsi' => 'Komik strip menghibur dengan sindiran sosial kehidupan anak muda Indonesia.',
                'jumlah_eksemplar' => 25,
                'cover_image' => 'si-juki.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Naruto Vol. 1',
                'penulis' => 'Masashi Kishimoto',
                'penerbit' => 'Elex Media Komputindo',
                'tahun_terbit' => '2008',
                'ISBN' => '9789792248661',
                'kategori' => 'Komik',
                'genre' => 'Fiction',
                'deskripsi' => 'Manga populer tentang Uzumaki Naruto, ninja muda bercita-cita jadi Hokage.',
                'jumlah_eksemplar' => 28,
                'cover_image' => 'naruto-1.jpg',
                'audience_category' => 'children',
                'created_at' => now(),
            ],
            [
                'judul' => 'One Piece Vol. 1',
                'penulis' => 'Eiichiro Oda',
                'penerbit' => 'Elex Media Komputindo',
                'tahun_terbit' => '2007',
                'ISBN' => '9789792247954',
                'kategori' => 'Komik',
                'genre' => 'Fiction',
                'deskripsi' => 'Petualangan Monkey D. Luffy mencari harta karun One Piece. Manga terlaris dunia.',
                'jumlah_eksemplar' => 30,
                'cover_image' => 'one-piece-1.jpg',
                'audience_category' => 'children',
                'created_at' => now(),
            ],
            [
                'judul' => 'Doraemon Vol. 1',
                'penulis' => 'Fujiko F. Fujio',
                'penerbit' => 'Elex Media Komputindo',
                'tahun_terbit' => '2005',
                'ISBN' => '9789792232714',
                'kategori' => 'Komik',
                'genre' => 'Fiction',
                'deskripsi' => 'Komik klasik tentang robot kucing dari masa depan yang membantu Nobita.',
                'jumlah_eksemplar' => 35,
                'cover_image' => 'doraemon-1.jpg',
                'audience_category' => 'children',
                'created_at' => now(),
            ],
            
            // Sains & Teknologi
            [
                'judul' => 'Brief Answers to the Big Questions',
                'penulis' => 'Stephen Hawking',
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => '2019',
                'ISBN' => '9786024526726',
                'kategori' => 'Ensiklopedia',
                'genre' => 'Education',
                'deskripsi' => 'Karya terakhir Stephen Hawking menjawab pertanyaan besar tentang alam semesta.',
                'jumlah_eksemplar' => 13,
                'cover_image' => 'brief-answers.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'Homo Deus: Masa Depan Umat Manusia',
                'penulis' => 'Yuval Noah Harari',
                'penerbit' => 'Pustaka Alvabet',
                'tahun_terbit' => '2018',
                'ISBN' => '9786024524616',
                'kategori' => 'Ensiklopedia',
                'genre' => 'Non-Fiction',
                'deskripsi' => 'Sekuel Sapiens tentang masa depan manusia di era AI dan bioengineering.',
                'jumlah_eksemplar' => 15,
                'cover_image' => 'homo-deus.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            
            // Ekonomi & Bisnis
            [
                'judul' => 'Rich Dad Poor Dad',
                'penulis' => 'Robert T. Kiyosaki',
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => '2017',
                'ISBN' => '9786020319889',
                'kategori' => 'Ensiklopedia',
                'genre' => 'Non-Fiction',
                'deskripsi' => 'Buku klasik literasi keuangan tentang mindset orang kaya vs orang miskin.',
                'jumlah_eksemplar' => 28,
                'cover_image' => 'rich-dad.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            [
                'judul' => 'The Lean Startup',
                'penulis' => 'Eric Ries',
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => '2018',
                'ISBN' => '9786024526108',
                'kategori' => 'Ensiklopedia',
                'genre' => 'Non-Fiction',
                'deskripsi' => 'Metodologi membangun startup dengan build-measure-learn cycle.',
                'jumlah_eksemplar' => 17,
                'cover_image' => 'lean-startup.jpg',
                'audience_category' => 'general',
                'created_at' => now(),
            ],
            
            // Pelajaran Sekolah
            [
                'judul' => 'Fisika untuk SMA Kelas X',
                'penulis' => 'Marthen Kanginan',
                'penerbit' => 'Erlangga',
                'tahun_terbit' => '2020',
                'ISBN' => '9786024341567',
                'kategori' => 'Komik',
                'genre' => 'Education',
                'deskripsi' => 'Buku pelajaran fisika lengkap untuk siswa SMA kelas 10 sesuai kurikulum.',
                'jumlah_eksemplar' => 40,
                'cover_image' => 'fisika-sma.jpg',
                'audience_category' => 'students',
                'created_at' => now(),
            ],
            [
                'judul' => 'Kimia untuk SMA Kelas X',
                'penulis' => 'Michael Purba',
                'penerbit' => 'Erlangga',
                'tahun_terbit' => '2020',
                'ISBN' => '9786024341574',
                'kategori' => 'Komik',
                'genre' => 'Education',
                'deskripsi' => 'Buku pelajaran kimia komprehensif untuk siswa SMA kelas 10.',
                'jumlah_eksemplar' => 40,
                'cover_image' => 'kimia-sma.jpg',
                'audience_category' => 'students',
                'created_at' => now(),
            ],
            [
                'judul' => 'Bahasa Indonesia untuk SMA',
                'penulis' => 'Tim Edukatif',
                'penerbit' => 'Erlangga',
                'tahun_terbit' => '2021',
                'ISBN' => '9786024341581',
                'kategori' => 'Komik',
                'genre' => 'Education',
                'deskripsi' => 'Buku pelajaran Bahasa Indonesia lengkap dengan latihan soal dan pembahasan.',
                'jumlah_eksemplar' => 45,
                'cover_image' => 'bahasa-indonesia.jpg',
                'audience_category' => 'students',
                'created_at' => now(),
            ],
        ];

        DB::table('books')->insert($books);
        
        $this->command->info('✅ Successfully seeded ' . count($books) . ' books!');
        $this->command->info('📚 Categories: Novel, Biografi, Ensiklopedia, Komik, Education');
        $this->command->info('👥 Audience: General, Children, Students');
    }
}
